"""Manage a Hermes Agent gateway (Docker) from the smartremote CLI.

Hermes runs as a container exposing its gateway on port 8642, with config in
~/.hermes (config.yaml + .env). We generate a docker-compose, collect the Email
(SMTP/IMAP) and WhatsApp channel settings, bring the gateway up/down, and wire
SmartRemote's notifier at the gateway URL.

NOTE: channel-config keys are aligned to the Hermes docs as of 2026-06 but may
differ across Hermes versions — verify against
https://github.com/NousResearch/hermes-agent and the docs/user-guide/messaging pages.
"""
from __future__ import annotations

import os
import shutil
import subprocess
import urllib.request
from pathlib import Path

import yaml

DEFAULT_IMAGE = "ghcr.io/nousresearch/hermes-agent:latest"  # verify tag with the repo
GATEWAY_PORT = 8642
HERMES_HOME = Path(os.environ.get("HERMES_HOME") or os.path.expanduser("~/.hermes"))

_COMPOSE = """\
# Generated by `smartremote hermes setup` — Hermes Agent gateway (Nous Research).
# Verify the image tag against https://github.com/NousResearch/hermes-agent
services:
  hermes:
    image: {image}
    command: gateway
    ports:
      - "{port}:{port}"
    volumes:
      - {hermes_home}:/root/.hermes
    restart: unless-stopped
"""


def compose_path(root: str | Path) -> Path:
    return Path(root) / "hermes" / "docker-compose.yml"


def write_compose(root: str | Path, image: str = DEFAULT_IMAGE, port: int = GATEWAY_PORT) -> Path:
    p = compose_path(root)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(_COMPOSE.format(image=image, port=port, hermes_home=HERMES_HOME), encoding="utf-8")
    return p


def write_channels(email: dict | None, whatsapp: bool) -> Path:
    """Write channel config to ~/.hermes/config.yaml; the email password to ~/.hermes/.env."""
    HERMES_HOME.mkdir(parents=True, exist_ok=True)
    cfg_path = HERMES_HOME / "config.yaml"
    cfg = yaml.safe_load(cfg_path.read_text(encoding="utf-8")) if cfg_path.exists() else {}
    cfg = cfg or {}
    channels = cfg.setdefault("channels", {})

    env_updates = {}
    if email:
        channels["email"] = {
            "enabled": True,
            "imap_host": email["imap_host"],
            "imap_port": int(email.get("imap_port", 993)),
            "smtp_host": email["smtp_host"],
            "smtp_port": int(email.get("smtp_port", 587)),
            "username": email["username"],
            # password is read from ~/.hermes/.env (HERMES_EMAIL_PASSWORD)
        }
        env_updates["HERMES_EMAIL_PASSWORD"] = email["password"]
    if whatsapp:
        # WhatsApp (Baileys) is paired via QR after the gateway starts.
        channels["whatsapp"] = {"enabled": True}

    cfg_path.write_text(
        "# Managed by `smartremote hermes setup` — verify keys against the Hermes docs.\n"
        + yaml.safe_dump(cfg, sort_keys=False),
        encoding="utf-8",
    )
    if env_updates:
        _merge_env(HERMES_HOME / ".env", env_updates)
    return cfg_path


def _merge_env(path: Path, updates: dict) -> None:
    lines = path.read_text(encoding="utf-8").splitlines() if path.exists() else []
    keep = [ln for ln in lines if "=" in ln and ln.split("=", 1)[0] not in updates]
    keep += [f"{k}={v}" for k, v in updates.items()]
    path.write_text("\n".join(keep) + "\n", encoding="utf-8")
    os.chmod(path, 0o600)  # secrets


def _compose_cmd() -> list[str] | None:
    if shutil.which("docker"):
        return ["docker", "compose"]
    if shutil.which("docker-compose"):
        return ["docker-compose"]
    return None


def up(root: str | Path) -> int:
    cc = _compose_cmd()
    if not cc:
        print("Docker not found. Install Docker, then re-run `smartremote hermes up`.")
        return 1
    return subprocess.call(cc + ["-f", str(compose_path(root)), "up", "-d"])


def down(root: str | Path) -> int:
    cc = _compose_cmd()
    if not cc:
        return 1
    return subprocess.call(cc + ["-f", str(compose_path(root)), "down"])


def health(base_url: str) -> tuple[int | None, str]:
    url = base_url.rstrip("/") + "/health"
    try:
        with urllib.request.urlopen(url, timeout=5) as r:  # noqa: S310
            return r.status, r.read(200).decode("utf-8", "replace")
    except Exception as e:  # noqa: BLE001
        return None, str(e)
